version: '3.5'
services:
  pgadmin:
    ports:
      - "5050:80"
    networks:
      - postgres-network
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-ii@project.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-ii_project}
    volumes:
       - pgadmin:/root/.pgadmin
       - ./pgadmin_config:/cfg
       - ./pgadmin_config/servers.json:/pgadmin4/servers.json
    restart: unless-stopped

  postgres:
    ports:
      - "5432:5432"
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ii}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ii_project}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres_config/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./postgres_config/2-create_tables.sql:/docker-entrypoint-initdb.d/2-create_tables.sql
      # Comment the line bellow to disable initial inserts into db
      - ./postgres_config/3-populate.sql:/docker-entrypoint-initdb.d/3-populate.sql
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
